font:
  size: 10
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

schemes:

  material-theme: &material-theme
    primary:
      background: '#263238'
      foreground: '#eeffff'

    # Normal colors
    normal:
      black:   '#000000'  # Arbitrary
      red:     '#e53935'
      green:   '#91b859'
      yellow:  '#ffb62c'
      blue:    '#6182b8'
      magenta: '#ff5370'  # Dark pink of the original material theme
      cyan:    '#39adb5'
      white:   '#a0a0a0'  # Arbitrary

    # Bright colors
    bright:
      black:   '#4e4e4e'  # Arbitrary
      red:     '#ff5370'
      green:   '#c3e88d'
      yellow:  '#ffcb6b'
      blue:    '#82aaff'
      magenta: '#f07178'  # Pink of the original material theme
      cyan:    '#89ddff'
      white:   '#ffffff'  # Arbitrary

  afterglow: &afterglow
    primary:
      background: '#2c2c2c'
      foreground: '#d6d6d6'

      dim_foreground:    '#dbdbdb'
      bright_foreground: '#d9d9d9'
      dim_background:    '#202020' # not sure
      bright_background: '#3a3a3a' # not sure

    # Cursor colors
    cursor:
      text:   '#2c2c2c'
      cursor: '#d9d9d9'

    # Normal colors
    normal:
      black:   '#1c1c1c'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#cacaca'

    # Bright colors
    bright:
      black:   '#636363'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#f7f7f7'

    # Dim colors
    dim:
      black:   '#232323'
      red:     '#74423f'
      green:   '#5e6547'
      yellow:  '#8b7653'
      blue:    '#556b79'
      magenta: '#6e4962'
      cyan:    '#5c8482'
      white:   '#828282'

  iterm: &iterm
    primary:
      background: '#101421'
      foreground: '#fffbf6'

  # Normal colors
    normal:
      black:   '#2e2e2e'
      red:     '#eb4129'
      green:   '#abe047'
      yellow:  '#f6c744'
      blue:    '#47a0f3'
      magenta: '#7b5cb0'
      cyan:    '#64dbed'
      white:   '#e5e9f0'

  # Bright colors
    bright:
      black:   '#565656'
      red:     '#ec5357'
      green:   '#c0e17d'
      yellow:  '#f9da6a'
      blue:    '#49a4f8'
      magenta: '#a47de9'
      cyan:    '#99faf2'
      white:   '#ffffff'

  molokai: &molokai
    # Default colors
    primary:
      background: '#1B1D1E'
      foreground: '#F8F8F2'
    # Normal colors
    normal:
      black:   '#333333'
      red:     '#C4265E'
      green:   '#86B42B'
      yellow:  '#B3B42B'
      blue:    '#6A7EC8'
      magenta: '#8C6BC8'
      cyan:    '#56ADBC'
      white:   '#E3E3DD'
    # Bright colors
    bright:
      black:   '#666666'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#E2E22E'
      blue:    '#819AFF'
      magenta: '#AE81FF'
      cyan:    '#66D9EF'
      white:   '#F8F8F2'

  one-dark: &one-dark
    primary:
      background: '#282c34'
      foreground: '#abb2bf'
    cursor:
      text:       CellBackground
      cursor:     '#528bff' # syntax-cursor-color
    selection:
      text:       CellForeground
      background: '#3e4451' # syntax-selection-color
    normal:
      black:      '#5c6370' # mono-3
      red:        '#e06c75' # red 1
      green:      '#98c379'
      yellow:     '#e5c07b' # orange 2
      blue:       '#61afef'
      magenta:    '#c678dd'
      cyan:       '#56b6c2'
      white:      '#828997' # mono-2

colors: *material-theme
